/* eslint-disable import/prefer-default-export */
export const gutter: string;
export const screensm: string;
export const screenmd: string;
export const screenlg: string;
export const screenxl: string;
export const addCollaboratorContainer: string;
export const addCollaboratorTable: string;
export const clickable: string;
export const selectRoleLabel: string;
export const iconDropdown: string;
export const iconRemove: string;
export const selectRoleLabelActive: string;
export const textCapitalize: string;
export const collaboratorDetail: string;
export const collaboratorInfo: string;
export const collaboratorName: string;
